# -*- coding: utf-8 -*-
"""narrative_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ldHt--ujjMoD9PzG8FkpLx_zDlyKSbo3
"""

from google.colab import drive
drive.mount('/content/drive')

import os
for root, dirs, files in os.walk("/content/drive"):
    pdfs = [f for f in files if f.endswith(".pdf")]
    if pdfs:
        print(f"{root}  →  {len(pdfs)} PDFs")

import subprocess, sys
for pkg in ["PyMuPDF"]:
    subprocess.check_call([sys.executable, "-m", "pip", "install", pkg, "-q"])
print("✓ Dependencies ready")


import os
import re
import json
from pathlib import Path
from collections import Counter

import pandas as pd
from tqdm import tqdm
import fitz  # PyMuPDF

BASE = "/content/drive/MyDrive/data sci capstone files"

PDF_DIRS = [
    "/content/drive/MyDrive/data sci capstone files/downloaded_pdfs_raw"
]

OUTPUT_DIR = BASE + "/pipeline_outputs"
MIN_WORDS   = 2000
YEAR_MIN    = 1980
YEAR_MAX    = 2024

os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f"✓ Config set")
print(f"  Input folders : {len(PDF_DIRS)}")
print(f"  Output dir    : {OUTPUT_DIR}")


# Helper Functions
def extract_text(path: str) -> str:
    """Extract raw text from PDF using PyMuPDF."""
    try:
        doc = fitz.open(path)
        text = "\n".join(page.get_text() for page in doc)
        doc.close()
        return text.strip()
    except Exception:
        return ""


def parse_metadata(filename: str) -> dict:
    """
    Extract title, writer, year from filename.
    Handles both formats:
      - Clean:  House-of-Dracula-(1945).pdf
      - Legacy: The Purge_James DeMonaco_Film_7 6 2011_____.pdf
    """
    stem = Path(filename).stem

    # Extract year from anywhere in filename
    year_match = re.search(r'\b(19[0-9]{2}|20[0-9]{2})', stem)
    year = int(year_match.group()) if year_match else None

    # Try legacy underscore format
    parts = stem.split("_")
    if len(parts) >= 3:
        title  = parts[0].strip()
        writer = parts[1].strip()
    else:
        # Clean format — derive title from stem
        title  = re.sub(r'\(\d{4}\)', '', stem)
        title  = re.sub(r'[-_]', ' ', title).strip()
        writer = "Unknown"

    return {
        "filename": filename,
        "title":    title,
        "writer":   writer,
        "year":     year,
    }


def era_label(year) -> str:
    if year is None or (isinstance(year, float) and pd.isna(year)):
        return "Unknown"
    year = int(year)
    if year <= 1979:   return "Pre-1980"
    if year <= 1995:   return "1980-1995 (Baseline)"
    if year <= 2009:   return "1996-2009"
    return "2010-Present"


def is_usable(text: str, filename: str) -> tuple[bool, str]:
    """
    Returns (True, 'ok') if script passes all quality checks.
    Returns (False, reason) if it should be filtered out.
    """
    # 1. Word count
    word_count = len(text.split())
    if word_count < MIN_WORDS:
        return False, f"too short ({word_count} words)"

    # 2. Year in filename
    year_match = re.search(r'\b(19[0-9]{2}|20[0-9]{2})', filename)
    if not year_match:
        return False, "no year in filename"

    # 3. Year in scope
    year = int(year_match.group())
    if year < YEAR_MIN or year > YEAR_MAX:
        return False, f"year {year} outside {YEAR_MIN}-{YEAR_MAX}"

    # 4. Script formatting indicators
    script_indicators = [
        'INT.', 'EXT.', 'FADE IN', 'FADE OUT',
        'CUT TO', 'DISSOLVE', 'INT ', 'EXT ',
        'SMASH CUT', 'MATCH CUT'
    ]
    has_format = any(ind in text.upper() for ind in script_indicators)
    is_outline  = any(w in filename.lower() for w in
                      ['outline', 'beat', 'treatment', 'beatsheet'])

    if not has_format and not is_outline:
        return False, "no script formatting detected"

    # 5. OCR quality check
    alpha_ratio = sum(c.isalpha() for c in text) / max(len(text), 1)
    if alpha_ratio < 0.4:
        return False, f"bad OCR (alpha ratio {alpha_ratio:.2f})"

    return True, "ok"


# Collect all PDF paths

all_pdfs = []
for folder in PDF_DIRS:
    if not os.path.exists(folder):
        print(f"⚠ Folder not found: {folder}")
        continue
    found = [os.path.join(folder, f)
             for f in os.listdir(folder)
             if f.lower().endswith(".pdf")]
    print(f"  {len(found):4d} PDFs  ←  {folder.split('/')[-1]}")
    all_pdfs.extend(found)

total_gb = sum(os.path.getsize(p) for p in all_pdfs) / 1e9
print(f"\n✓ Total: {len(all_pdfs)} PDFs ({total_gb:.1f} GB)")


all_pdfs = all_pdfs[:1000]
records  = []
skipped  = {}

for fpath in tqdm(all_pdfs, desc="Filtering"):
    fname = os.path.basename(fpath)
    text  = extract_text(fpath)
    usable, reason = is_usable(text, fname)

    if not usable:
        skipped[fname] = reason
        continue

    meta = parse_metadata(fname)
    meta["full_path"]   = fpath
    meta["word_count"]  = len(text.split())
    meta["era"]         = era_label(meta["year"])
    meta["source_folder"] = Path(fpath).parent.name
    records.append(meta)


# Save outputs
usable_df  = pd.DataFrame(records)
filter_log = pd.DataFrame([
    {"filename": k, "reason": v} for k, v in skipped.items()
])

usable_path = os.path.join(OUTPUT_DIR, "usable_scripts.csv")
filter_path = os.path.join(OUTPUT_DIR, "filter_log.csv")

usable_df.to_csv(usable_path, index=False)
filter_log.to_csv(filter_path, index=False)

print(f"✓ Saved usable_scripts.csv  ({len(usable_df)} scripts)")
print(f"✓ Saved filter_log.csv      ({len(filter_log)} filtered out)")



print("\n" + "=" * 55)
print("FILTER SUMMARY")
print("=" * 55)
print(f"  Total PDFs scanned : {len(all_pdfs)}")
print(f"  Usable scripts     : {len(usable_df)}")
print(f"  Filtered out       : {len(skipped)}")
print(f"  Pass rate          : {len(usable_df)/max(len(all_pdfs),1)*100:.1f}%")

print(f"\nTop filter reasons:")
for reason, count in Counter(skipped.values()).most_common(8):
    print(f"  {count:4d} × {reason}")

print(f"\nEra distribution (usable scripts):")
print(usable_df["era"].value_counts().to_string())

print(f"\nYear range : {usable_df['year'].min():.0f} – {usable_df['year'].max():.0f}")
print(f"Avg words  : {usable_df['word_count'].mean():.0f}")

print(f"\nSource folder breakdown:")
print(usable_df["source_folder"].value_counts().to_string())

print(f"\nOutput files:")
print(f"  {usable_path}")
print(f"  {filter_path}")
print("=" * 55)
print("\n✓ Ready to run narrative_pipeline.py")

import subprocess, sys

packages = [
    "PyMuPDF",           # PDF text extraction (fitz)
    "nltk",
    "transformers",
    "torch",
    "sentence-transformers",
    "umap-learn",
    "scikit-learn",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scipy",
    "tqdm",
]

for pkg in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", pkg, "-q"])

print("✓ All packages installed")

# imports and config
import os, re, json, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
from pathlib import Path
from collections import Counter

from scipy.stats import entropy as scipy_entropy, mannwhitneyu
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.metrics import (silhouette_score, adjusted_rand_score,
                              classification_report, confusion_matrix,
                              ConfusionMatrixDisplay)
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download("vader_lexicon", quiet=True)
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)

import fitz  # PyMuPDF

warnings.filterwarnings("ignore")

# ── CONFIG ────────────────────────────────────────────────────
BASE           = "/content/drive/MyDrive/data sci capstone files"
USABLE_CSV     = BASE + "/pipeline_outputs/usable_scripts.csv"   # output of filter_pipeline.py
OUTPUT_DIR     = BASE + "/pipeline_outputs"
N_SEGMENTS     = 10        # narrative segments per film
EMBED_BATCH    = 16        # sentence-transformer batch size
BASELINE_END   = 1995      # baseline era cutoff year
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"✓ Config set")
print(f"  Reading from  : {USABLE_CSV}")
print(f"  Output dir    : {OUTPUT_DIR}")
print(f"  Segments      : {N_SEGMENTS}")
print(f"  Baseline era  : ≤ {BASELINE_END}")

# Load pre-filtered scripts from CSV

def extract_text_from_pdf(path: str) -> str:
    """Extract raw text from a PDF using PyMuPDF."""
    try:
        doc = fitz.open(path)
        text = "\n".join(page.get_text() for page in doc)
        doc.close()
        return text.strip()
    except Exception:
        return ""


def era_label(year) -> str:
    if year is None or (isinstance(year, float) and pd.isna(year)):
        return "Unknown"
    year = int(year)
    if year <= 1979:   return "Pre-1980"
    if year <= 1995:   return "1980-1995 (Baseline)"
    if year <= 2009:   return "1996-2009"
    return "2010-Present"


print("Loading usable scripts from filter_pipeline output...")

# Read the pre-filtered metadata CSV
meta_df = pd.read_csv(USABLE_CSV)
print(f"  Found {len(meta_df)} usable scripts in CSV")

# Now load the actual text for each script
records = []
skipped = 0

for _, row in tqdm(meta_df.iterrows(), total=len(meta_df), desc="Loading text"):
    fpath = row.get("full_path")
    if not fpath or not os.path.exists(str(fpath)):
        skipped += 1
        continue

    text = extract_text_from_pdf(str(fpath))
    if not text or len(text.split()) < 2000:
        skipped += 1
        continue

    records.append({
        "title":      row.get("title", "Unknown"),
        "writer":     row.get("writer", "Unknown"),
        "year":       row.get("year"),
        "filename":   row.get("filename"),
        "word_count": row.get("word_count"),
        "text":       text,
    })

df = pd.DataFrame(records)
df["era"] = df["year"].apply(lambda y: era_label(y) if pd.notna(y) else "Unknown")

print(f"\n✓ Scripts loaded  : {len(df)}")
print(f"  Skipped         : {skipped} (file not found or too short)")
print(f"  Year range      : {df['year'].min():.0f} – {df['year'].max():.0f}")
print(f"  Avg word count  : {df['word_count'].mean():.0f}")
print(f"\nEra distribution:")
print(df["era"].value_counts().to_string())

import os

BASE = "/content/drive/MyDrive/data sci capstone files"
for root, dirs, files in os.walk(BASE):
    for f in files:
        if f == "usable_scripts.csv":
            print(os.path.join(root, f))

sia = SentimentIntensityAnalyzer()

def get_sentiment_arc(text: str, n_segments: int = N_SEGMENTS) -> np.ndarray:
    """
    Split script into n equal segments, compute mean VADER compound
    sentiment score per segment. Returns array of shape (n_segments,).
    """
    sentences = nltk.sent_tokenize(text)
    if len(sentences) < n_segments:
        return None

    seg_size = len(sentences) // n_segments
    arc = []
    for i in range(n_segments):
        seg = sentences[i * seg_size: (i + 1) * seg_size]
        scores = [sia.polarity_scores(s)["compound"] for s in seg]
        arc.append(np.mean(scores))

    return np.array(arc)


print("Computing sentiment arcs...")
arcs = []
valid_indices = []

for idx, row in tqdm(df.iterrows(), total=len(df), desc="Sentiment arcs"):
    arc = get_sentiment_arc(row["text"])
    if arc is not None:
        arcs.append(arc)
        valid_indices.append(idx)

df = df.loc[valid_indices].reset_index(drop=True)
arc_matrix = np.array(arcs)  # shape: (n_films, N_SEGMENTS)

print(f"✓ Sentiment arcs computed for {len(df)} films")
print(f"  Arc matrix shape: {arc_matrix.shape}")

np.save(os.path.join(OUTPUT_DIR, "sentiment_arcs.npy"), arc_matrix)

"""### Average Sentiment Arcs by ERa"""

def era_label(year):
    if year is None:   return "Unknown"
    if year <= 1979:   return "Pre-1980"
    if year <= 1995:   return "1980–1995 (Baseline)"
    if year <= 2009:   return "1996–2009"
    return "2010–Present"

df["era"] = df["year"].apply(era_label)
era_order = ["Pre-1980", "1980–1995 (Baseline)", "1996–2009", "2010–Present"]
colors    = ["#4e79a7", "#f28e2b", "#59a14f", "#e15759"]

fig, ax = plt.subplots(figsize=(12, 5))
x = np.arange(1, N_SEGMENTS + 1)

for era, color in zip(era_order, colors):
    mask = df["era"] == era
    if mask.sum() == 0:
        continue
    era_arcs = arc_matrix[mask.values]
    mean_arc = era_arcs.mean(axis=0)
    std_arc  = era_arcs.std(axis=0)
    ax.plot(x, mean_arc, label=f"{era} (n={mask.sum()})", color=color, lw=2.5)
    ax.fill_between(x, mean_arc - std_arc, mean_arc + std_arc, alpha=0.12, color=color)

ax.axhline(0, color="gray", lw=0.8, ls="--")
ax.set_xlabel("Narrative Segment (1=Opening → 10=Ending)", fontsize=12)
ax.set_ylabel("Mean VADER Compound Sentiment", fontsize=12)
ax.set_title("Average Sentiment Arc by Era\n(Are emotional trajectories converging?)", fontsize=14, fontweight="bold")
ax.legend(fontsize=10)
ax.set_xticks(x)
sns.despine(ax=ax)
plt.tight_layout()
plt.show()

"""### Narrative Arc Similarity"""

# Metric 1 — Narrative Arc Similarity
# Cosine similarity between all pairs of sentiment arcs.
# Higher mean similarity = more homogenized narratives.

print("\nComputing Narrative Arc Similarity matrix...")
sim_matrix = cosine_similarity(arc_matrix)  # (n_films, n_films)

# Mean similarity per era (excluding self-similarity diagonal)
results = []
for era in era_order:
    mask = (df["era"] == era).values
    if mask.sum() < 2:
        continue
    sub = sim_matrix[np.ix_(mask, mask)]
    np.fill_diagonal(sub, np.nan)
    mean_sim = np.nanmean(sub)
    std_sim  = np.nanstd(sub)
    results.append({"Era": era, "N": mask.sum(),
                    "Mean Arc Similarity": round(mean_sim, 4),
                    "Std": round(std_sim, 4)})

sim_df = pd.DataFrame(results)
print("\nNarrative Arc Similarity by Era:")
print(sim_df.to_string(index=False))
sim_df.to_csv(os.path.join(OUTPUT_DIR, "metric1_arc_similarity.csv"), index=False)

# Plot
fig, ax = plt.subplots(figsize=(8, 4))
eras_present = sim_df["Era"].tolist()
vals = sim_df["Mean Arc Similarity"].values
errs = sim_df["Std"].values
bar_colors = [colors[era_order.index(e)] for e in eras_present]

bars = ax.bar(eras_present, vals, color=bar_colors, edgecolor="white", width=0.5)
ax.errorbar(range(len(vals)), vals, yerr=errs, fmt="none", color="black", capsize=4)

# Baseline reference line
baseline_val = sim_df[sim_df["Era"] == "1980–1995 (Baseline)"]["Mean Arc Similarity"].values
if len(baseline_val):
    ax.axhline(baseline_val[0], color="orange", ls="--", lw=1.5, label="Baseline (1980–1995)")
    ax.legend()

ax.set_ylabel("Mean Cosine Similarity", fontsize=11)
ax.set_title("Metric 1: Narrative Arc Similarity by Era\n(Higher = more homogenized)", fontsize=13, fontweight="bold")
ax.set_ylim(0, 1)
plt.xticks(rotation=15, ha="right")
sns.despine(ax=ax)
plt.tight_layout()
#plt.savefig(os.path.join(OUTPUT_DIR, "02_narrative_arc_similarity.png"), dpi=150)
plt.show()
#print("✓ Saved 02_narrative_arc_similarity.png")

# Metric 2 — Narrative Transition Entropy
# Entropy of the distribution of sentiment changes between segments.
# Low entropy = predictable/formulaic transitions.

def transition_entropy(arc: np.ndarray) -> float:
    """
    Compute entropy of discretized sentiment transitions.
    Transitions: UP (+), FLAT (=), DOWN (-)
    """
    diffs = np.diff(arc)
    bins = np.array([-1 if d < -0.05 else (1 if d > 0.05 else 0) for d in diffs])
    counts = np.array([(bins == v).sum() for v in [-1, 0, 1]], dtype=float)
    counts = counts[counts > 0]
    probs = counts / counts.sum()
    return float(scipy_entropy(probs, base=2))


df["transition_entropy"] = [transition_entropy(arc) for arc in arc_matrix]

entropy_by_era = df.groupby("era")["transition_entropy"].agg(["mean", "std", "count"]).reindex(era_order).dropna()
print("\nNarrative Transition Entropy by Era:")
print(entropy_by_era.round(4))
entropy_by_era.to_csv(os.path.join(OUTPUT_DIR, "metric2_transition_entropy.csv"))

fig, ax = plt.subplots(figsize=(8, 4))
eras_e = entropy_by_era.index.tolist()
bar_colors_e = [colors[era_order.index(e)] for e in eras_e]
ax.bar(eras_e, entropy_by_era["mean"], color=bar_colors_e, edgecolor="white", width=0.5)
ax.errorbar(range(len(eras_e)), entropy_by_era["mean"], yerr=entropy_by_era["std"],
            fmt="none", color="black", capsize=4)
ax.set_ylabel("Mean Transition Entropy (bits)", fontsize=11)
ax.set_title("Metric 2: Narrative Transition Entropy by Era\n(Lower = more formulaic structure)", fontsize=13, fontweight="bold")
ax.set_ylim(0, 1.8)
plt.xticks(rotation=15, ha="right")
sns.despine(ax=ax)
plt.tight_layout()
#plt.savefig(os.path.join(OUTPUT_DIR, "03_transition_entropy.png"), dpi=150)
plt.show()
#print("✓ Saved 03_transition_entropy.png")

# Similarity Heatmap

# Sort films by year for a coherent heatmap
df_sorted = df.sort_values("year").reset_index(drop=True)
sort_idx  = df_sorted.index.tolist()

# Reorder sim_matrix
orig_positions = [df.index.get_loc(i) for i in df_sorted.index]
sim_sorted = sim_matrix[np.ix_(orig_positions, orig_positions)]

fig, ax = plt.subplots(figsize=(10, 8))
im = ax.imshow(sim_sorted, cmap="RdYlGn", vmin=0, vmax=1, aspect="auto")
plt.colorbar(im, ax=ax, label="Cosine Similarity")
ax.set_title("Narrative Arc Similarity Heatmap\n(Films sorted by year — diagonal = self)", fontsize=13, fontweight="bold")
ax.set_xlabel("Film Index (chronological)")
ax.set_ylabel("Film Index (chronological)")
plt.tight_layout()
#plt.savefig(os.path.join(OUTPUT_DIR, "04_similarity_heatmap.png"), dpi=150)
plt.show()
#print("✓ Saved 04_similarity_heatmap.png")

"""### BERT Embeddings and UMAP"""

from sentence_transformers import SentenceTransformer
import umap

print("\nLoading sentence-transformer model (all-MiniLM-L6-v2)...")
embedder = SentenceTransformer("all-MiniLM-L6-v2")

def sample_text(text: str, max_chars: int = 8000) -> str:
    """Take middle portion of script (avoids credits/copyright at start/end)."""
    if len(text) <= max_chars:
        return text
    mid = len(text) // 2
    half = max_chars // 2
    return text[mid - half: mid + half]

print("Generating embeddings (this may take a few minutes)...")
texts_sampled = [sample_text(t) for t in df["text"].tolist()]
embeddings = embedder.encode(
    texts_sampled,
    batch_size=EMBED_BATCH,
    show_progress_bar=True,
    convert_to_numpy=True
)
print(f"✓ Embeddings shape: {embeddings.shape}")
#np.save(os.path.join(OUTPUT_DIR, "bert_embeddings.npy"), embeddings)

# UMAP reduction
print("Running UMAP dimensionality reduction...")
reducer = umap.UMAP(n_components=2, random_state=42, n_neighbors=10, min_dist=0.1)
embedding_2d = reducer.fit_transform(embeddings)
#np.save(os.path.join(OUTPUT_DIR, "umap_2d.npy"), embedding_2d)

# Plot
fig, ax = plt.subplots(figsize=(11, 8))
era_color_map = dict(zip(era_order, colors))

for era in era_order:
    mask = df["era"] == era
    if mask.sum() == 0:
        continue
    pts = embedding_2d[mask.values]
    ax.scatter(pts[:, 0], pts[:, 1],
               label=f"{era} (n={mask.sum()})",
               color=era_color_map[era],
               alpha=0.75, s=60, edgecolors="white", lw=0.4)

ax.set_title("BERT Embedding Space — Films by Era\n(Clusters = narrative similarity; convergence = tighter grouping over time)",
             fontsize=13, fontweight="bold")
ax.set_xlabel("UMAP Dimension 1")
ax.set_ylabel("UMAP Dimension 2")
ax.legend(fontsize=9, framealpha=0.7)
sns.despine(ax=ax)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "05_umap_embedding_space.png"), dpi=150)
plt.show()
print("✓ Saved 05_umap_embedding_space.png")

np.save(os.path.join(OUTPUT_DIR, "bert_embeddings.npy"), embeddings)

"""### Genere Convergence Ratio"""

#Genre Convergence Ratio
# For each era: within-era similarity vs. cross-era similarity.
# Ratio > 1 means within-era films are more similar than across eras (convergence).
# We proxy "genre" with era since genre labels aren't in ScriptHive metadata.

print("\nComputing Genre Convergence Ratio...")

gcr_results = []
for era in era_order:
    mask = (df["era"] == era).values
    if mask.sum() < 2:
        continue

    # Within-era similarity
    within = sim_matrix[np.ix_(mask, mask)]
    np.fill_diagonal(within, np.nan)
    within_mean = np.nanmean(within)

    # Cross-era similarity
    cross = sim_matrix[np.ix_(mask, ~mask)]
    cross_mean = np.nanmean(cross)

    gcr = within_mean / cross_mean if cross_mean > 0 else np.nan
    gcr_results.append({
        "Era": era,
        "N": mask.sum(),
        "Within-Era Similarity": round(within_mean, 4),
        "Cross-Era Similarity": round(cross_mean, 4),
        "Convergence Ratio (GCR)": round(gcr, 4),
    })

gcr_df = pd.DataFrame(gcr_results)
print("\nGenre Convergence Ratio by Era:")
print(gcr_df.to_string(index=False))
gcr_df.to_csv(os.path.join(OUTPUT_DIR, "metric3_convergence_ratio.csv"), index=False)

fig, ax = plt.subplots(figsize=(8, 4))
eras_g = gcr_df["Era"].tolist()
gcr_vals = gcr_df["Convergence Ratio (GCR)"].values
bar_colors_g = [colors[era_order.index(e)] for e in eras_g]
bars = ax.bar(eras_g, gcr_vals, color=bar_colors_g, edgecolor="white", width=0.5)
ax.axhline(1.0, color="black", ls="--", lw=1.2, label="GCR = 1 (no convergence)")
ax.set_ylabel("Convergence Ratio", fontsize=11)
ax.set_title("Metric 3: Genre/Era Convergence Ratio\n(>1 = within-era more similar than cross-era)", fontsize=13, fontweight="bold")
ax.legend()
plt.xticks(rotation=15, ha="right")
sns.despine(ax=ax)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "06_convergence_ratio.png"), dpi=150)
plt.show()
print("✓ Saved 06_convergence_ratio.png")

"""### Similarity Over Time"""

print("\nComputing year-by-year similarity trend...")
df_year = df[df["year"].notna()].copy()
df_year["year"] = df_year["year"].astype(int)

year_sim = []
years_sorted = sorted(df_year["year"].unique())

for yr in years_sorted:
    mask = (df_year["year"] == yr).values
    if mask.sum() < 2:
        continue
    idxs = df_year[df_year["year"] == yr].index.tolist()
    orig_idxs = [df.index.get_loc(i) for i in idxs]
    sub = sim_matrix[np.ix_(orig_idxs, orig_idxs)]
    np.fill_diagonal(sub, np.nan)
    year_sim.append({"year": yr, "mean_sim": np.nanmean(sub), "n": mask.sum()})

year_sim_df = pd.DataFrame(year_sim)

if len(year_sim_df) > 3:
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.scatter(year_sim_df["year"], year_sim_df["mean_sim"],
               s=year_sim_df["n"] * 15, alpha=0.6, color="#4e79a7", edgecolors="white")

    # Rolling trend line (window=3 years)
    rolling = year_sim_df.set_index("year")["mean_sim"].rolling(3, min_periods=1).mean()
    ax.plot(rolling.index, rolling.values, color="#e15759", lw=2.5, label="3-yr rolling mean")

    ax.axvline(BASELINE_END, color="orange", ls="--", lw=1.5, label=f"Baseline cutoff ({BASELINE_END})")
    ax.set_xlabel("Year", fontsize=12)
    ax.set_ylabel("Mean Pairwise Arc Similarity", fontsize=12)
    ax.set_title("Narrative Similarity Over Time\n(Bubble size = number of films that year)", fontsize=13, fontweight="bold")
    ax.legend()
    sns.despine(ax=ax)
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "07_similarity_over_time.png"), dpi=150)
    plt.show()
    print("✓ Saved 07_similarity_over_time.png")
    year_sim_df.to_csv(os.path.join(OUTPUT_DIR, "year_similarity_trend.csv"), index=False)

"""### Summary Report"""

print("\n" + "=" * 60)
print("PIPELINE COMPLETE — SUMMARY")
print("=" * 60)
print(f"  Scripts analyzed     : {len(df)}")
print(f"  Year range           : {int(df['year'].min())} – {int(df['year'].max())}")
print(f"  Baseline era (≤{BASELINE_END}) : {(df['year'] <= BASELINE_END).sum()} films")
print(f"  Post-baseline        : {(df['year'] > BASELINE_END).sum()} films")

print("\n── Metric 1: Narrative Arc Similarity ──")
print(sim_df[["Era", "N", "Mean Arc Similarity"]].to_string(index=False))

print("\n── Metric 2: Narrative Transition Entropy ──")
print(entropy_by_era[["mean", "count"]].rename(columns={"mean": "Avg Entropy", "count": "N"}).to_string())

print("\n── Metric 3: Genre Convergence Ratio ──")
print(gcr_df[["Era", "N", "Convergence Ratio (GCR)"]].to_string(index=False))

print(f"\n── Output files saved to ./{OUTPUT_DIR}/ ──")
for f in sorted(os.listdir(OUTPUT_DIR)):
    print(f"  {f}")

print("\n" + "=" * 60)
print("KEY INTERPRETATION GUIDE")
print("=" * 60)
print("""
  Narrative Arc Similarity  → Higher in recent eras = homogenization detected
  Transition Entropy        → Lower in recent eras = more formulaic structure
  Genre Convergence Ratio   → Rising over time = genre boundaries dissolving
  UMAP plot                 → Tighter clusters for recent films = convergence

  Compare all metrics against the 1980–1995 baseline.
  A ≥20% increase in Arc Similarity meets the project's success threshold.
""")

"""## Modeling BERT + KMeans as Baseline"""

import numpy as np
import pandas as pd

BASE       = "/content/drive/MyDrive/data sci capstone files"
OUTPUT_DIR = BASE + "/pipeline_outputs"

# Load saved outputs
arc_matrix = np.load(OUTPUT_DIR + "/sentiment_arcs.npy")
df         = pd.read_csv(OUTPUT_DIR + "/usable_scripts.csv")
embeddings = np.load(OUTPUT_DIR + "/bert_embeddings.npy")

print(f"Loaded {len(df)} scripts")

print("\n" + "=" * 60)
print("BASELINE MODEL: BERT + KMeans Clustering")
print("=" * 60)

ERA_ORDER = ["Pre-1980", "1980-1995 (Baseline)", "1996-2009", "2010-Present"]
COLORS    = ["#4e79a7", "#f28e2b", "#59a14f", "#e15759"]
era_color_map = dict(zip(ERA_ORDER, COLORS))

kmeans        = KMeans(n_clusters=4, random_state=42, n_init=10)
df["cluster"] = kmeans.fit_predict(embeddings)

sil_score = silhouette_score(embeddings, df["cluster"])
le_era    = LabelEncoder()
era_int   = le_era.fit_transform(df["era"].values)
ari_score = adjusted_rand_score(era_int, df["cluster"])

print(f"\n  Silhouette Score     : {sil_score:.4f}")
print(f"  Adjusted Rand Index  : {ari_score:.4f}")
print(f"  (ARI: 0=random, 1=perfect era alignment)")

crosstab = pd.crosstab(df["cluster"], df["era"],
                        rownames=["Cluster"], colnames=["Era"])
print(f"\n  Cluster x Era distribution:")
print(crosstab.to_string())
crosstab.to_csv(os.path.join(OUTPUT_DIR, "baseline_cluster_crosstab.csv"))

# Side-by-side UMAP: clusters vs true eras
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
cluster_colors = ["#e15759", "#4e79a7", "#59a14f", "#f28e2b"]

for c in range(4):
    mask = df["cluster"] == c
    pts  = embedding_2d[mask.values]
    axes[0].scatter(pts[:, 0], pts[:, 1], label=f"Cluster {c} (n={mask.sum()})",
                    color=cluster_colors[c], alpha=0.75, s=60, edgecolors="white", lw=0.4)
axes[0].set_title("KMeans Clusters (Baseline Model)\nUnsupervised — no era labels used",
                   fontweight="bold")
axes[0].legend(fontsize=9)
sns.despine(ax=axes[0])

for era in ERA_ORDER:
    mask = df["era"] == era
    if mask.sum() == 0: continue
    pts = embedding_2d[mask.values]
    axes[1].scatter(pts[:, 0], pts[:, 1], label=f"{era} (n={mask.sum()})",
                    color=era_color_map[era], alpha=0.75, s=60, edgecolors="white", lw=0.4)
axes[1].set_title("True Era Labels\n(For comparison with clusters)", fontweight="bold")
axes[1].legend(fontsize=9)
sns.despine(ax=axes[1])

plt.suptitle(f"Baseline: BERT + KMeans  |  Silhouette={sil_score:.3f}  |  ARI={ari_score:.3f}",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "02_baseline_kmeans.png"), dpi=150)
plt.show()
print("✓ Saved 02_baseline_kmeans.png")

with open(os.path.join(OUTPUT_DIR, "baseline_model_results.json"), "w") as f:
    json.dump({"model": "BERT + KMeans", "silhouette": float(sil_score),
               "ari": float(ari_score)}, f, indent=2)
print("✓ Saved baseline_model_results.json")

print(df.columns.tolist())

"""## Improved - Random Forest

"""

print("\n" + "=" * 60)
print("IMPROVED MODEL: Random Forest Era Classifier")
print("=" * 60)

df_model = df[df["era"].isin(["1980-1995 (Baseline)", "2010-Present"])].copy()
print(f"  Scripts: {len(df_model)}")
print(df_model["era"].value_counts().to_string())

arc_df   = pd.DataFrame(arc_matrix[df_model.index],
                         columns=[f"arc_{i}" for i in range(N_SEGMENTS)],
                         index=df_model.index)
df_model = pd.concat([df_model, arc_df], axis=1)
feature_cols = [f"arc_{i}" for i in range(N_SEGMENTS)]

X  = df_model[feature_cols].fillna(0).values
le = LabelEncoder()
y  = le.fit_transform(df_model["era"].values)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# SMOTE to fix class imbalance
sm = SMOTE(random_state=42)
X_train_bal, y_train_bal = sm.fit_resample(X_train, y_train)
print(f"\n  After SMOTE: {Counter(y_train_bal)}")

rf = RandomForestClassifier(n_estimators=200, random_state=42, class_weight="balanced")
rf.fit(X_train_bal, y_train_bal)
y_pred_rf = rf.predict(X_test)

lr = LogisticRegression(max_iter=1000, random_state=42, class_weight="balanced")
lr.fit(X_train_bal, y_train_bal)
y_pred_lr = lr.predict(X_test)

n_splits = min(5, len(df_model) // 4)
cv_rf = cross_val_score(rf, X, y, cv=n_splits, scoring="f1_weighted")
cv_lr = cross_val_score(lr, X, y, cv=n_splits, scoring="f1_weighted")

print(f"\n── Random Forest ──")
print(classification_report(y_test, y_pred_rf, target_names=le.classes_, zero_division=0))
print(f"  CV F1: {cv_rf.mean():.3f} ± {cv_rf.std():.3f}")

print(f"\n── Logistic Regression ──")
print(classification_report(y_test, y_pred_lr, target_names=le.classes_, zero_division=0))
print(f"  CV F1: {cv_lr.mean():.3f} ± {cv_lr.std():.3f}")

# Confusion matrix
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for ax, y_p, title in zip(axes, [y_pred_rf, y_pred_lr],
                            ["Random Forest (Improved)", "Logistic Regression"]):
    cm = confusion_matrix(y_test, y_p)
    ConfusionMatrixDisplay(cm, display_labels=le.classes_).plot(
        ax=ax, colorbar=False, cmap="Blues")
    ax.set_title(title, fontweight="bold")
    ax.tick_params(axis="x", rotation=15)
plt.suptitle("Improved Model: Era Classification", fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "03_improved_confusion_matrix.png"), dpi=150)
plt.show()
print("✓ Saved 03_improved_confusion_matrix.png")

# Feature importance
feat_imp = pd.Series(rf.feature_importances_, index=feature_cols).sort_values(ascending=False)
fig, ax = plt.subplots(figsize=(10, 4))
feat_imp.plot(kind="bar", ax=ax, color="#4e79a7", edgecolor="white")
ax.set_title("Feature Importance — Which story positions distinguish eras?",
             fontweight="bold")
ax.set_ylabel("Importance")
plt.xticks(rotation=0)
sns.despine(ax=ax)
plt.tight_layout()
plt.show()

"""### Clustering - KMeans"""

# Build full arc feature matrix for all films
arc_full_df = pd.DataFrame(arc_matrix,
    columns=[f"arc_{i}" for i in range(N_SEGMENTS)])
X_cluster = arc_full_df.values

# Fit KMeans with k=4 (matching our 4 eras)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df["cluster"] = kmeans.fit_predict(X_cluster)

sil_score = silhouette_score(X_cluster, df["cluster"])
print(f"  Silhouette Score: {sil_score:.4f}")
print(f"  (Range -1 to 1. Higher = tighter, more distinct clusters)")
print(f"\n  Cluster distribution:")
print(df["cluster"].value_counts().to_string())

# Cluster vs Era crosstab
crosstab = pd.crosstab(df["cluster"], df["era"])
print(f"\n  Cluster × Era crosstab:")
print(crosstab.to_string())
crosstab.to_csv(os.path.join(OUTPUT_DIR, "cluster_era_crosstab.csv"))

# Silhouette score per era (how tightly films cluster within era)
sil_by_era = {}
for era in era_order:
    mask = df["era"] == era
    if mask.sum() < 2:
        continue
    era_X = X_cluster[mask.values]
    era_labels = df["cluster"][mask.values]
    if len(np.unique(era_labels)) > 1:
        sil_by_era[era] = silhouette_score(era_X, era_labels)
    else:
        sil_by_era[era] = np.nan

print(f"\n  Silhouette score per era (higher = tighter clustering):")
for era, score in sil_by_era.items():
    print(f"    {era}: {score:.4f}" if not np.isnan(score) else f"    {era}: N/A")

print("\n" + "="*55)
print("PERFORMANCE EVALUATION — Statistical Tests")
print("="*55)

# Extract pairwise similarities per era
def era_similarities(era_name):
    mask = (df["era"] == era_name).values
    if mask.sum() < 2:
        return np.array([])
    sub = sim_matrix[np.ix_(mask, mask)]
    np.fill_diagonal(sub, np.nan)
    return sub[~np.isnan(sub)].flatten()

baseline_sims = era_similarities("1980-1995 (Baseline)")
modern_sims   = era_similarities("2010-Present")
mid_sims      = era_similarities("1996-2009")

print(f"\n  Baseline (1980-1995) : n={len(baseline_sims)}, mean={np.mean(baseline_sims):.4f}")
print(f"  Mid-era  (1996-2009) : n={len(mid_sims)},  mean={np.mean(mid_sims):.4f}")
print(f"  Modern   (2010+)     : n={len(modern_sims)}, mean={np.mean(modern_sims):.4f}")

# Mann-Whitney U: is modern similarity significantly higher than baseline?
if len(baseline_sims) > 0 and len(modern_sims) > 0:
    stat, p_val = mannwhitneyu(modern_sims, baseline_sims, alternative="greater")
    print(f"\n  Mann-Whitney U Test (Modern > Baseline):")
    print(f"    U statistic : {stat:.2f}")
    print(f"    p-value     : {p_val:.4f}")
    if p_val < 0.05:
        print(f"    ✓ SIGNIFICANT — Modern films are statistically more similar (p < 0.05)")
        print(f"      → Evidence supports narrative homogenization hypothesis")
    else:
        print(f"    ✗ NOT SIGNIFICANT — No statistically detectable convergence (p ≥ 0.05)")
        print(f"      → Insufficient evidence for narrative homogenization")

# Check ≥20% increase threshold from charter
if len(baseline_sims) > 0 and len(modern_sims) > 0:
    baseline_mean = np.mean(baseline_sims)
    modern_mean   = np.mean(modern_sims)
    pct_change    = (modern_mean - baseline_mean) / baseline_mean * 100
    print(f"\n  Charter Success Threshold (≥20% increase in Arc Similarity):")
    print(f"    Baseline mean : {baseline_mean:.4f}")
    print(f"    Modern mean   : {modern_mean:.4f}")
    print(f"    Change        : {pct_change:+.1f}%")
    if pct_change >= 20:
        print(f"    ✓ THRESHOLD MET — {pct_change:.1f}% increase exceeds 20% target")
    else:
        print(f"    ✗ THRESHOLD NOT MET — {pct_change:.1f}% change below 20% target")

# Save stats summary
stats_summary = {
    "baseline_mean_similarity": float(np.mean(baseline_sims)) if len(baseline_sims) > 0 else None,
    "modern_mean_similarity":   float(np.mean(modern_sims))   if len(modern_sims) > 0 else None,
    "pct_change":               float(pct_change)             if len(baseline_sims) > 0 and len(modern_sims) > 0 else None,
    "mannwhitney_p":            float(p_val)                  if len(baseline_sims) > 0 and len(modern_sims) > 0 else None,
    "silhouette_score":         float(sil_score),
    "rf_cv_f1":                 float(cv_rf.mean()),
    "lr_cv_f1":                 float(cv_lr.mean()),
}